// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ChatRoom defines model for ChatRoom.
type ChatRoom struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ChatRoomCreate defines model for ChatRoomCreate.
type ChatRoomCreate struct {
	Name *string `json:"name,omitempty"`
}

// CreateChatRoomJSONRequestBody defines body for CreateChatRoom for application/json ContentType.
type CreateChatRoomJSONRequestBody = ChatRoomCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available chat rooms
	// (GET /rooms)
	ListChatRooms(ctx echo.Context) error
	// Create a new chat room
	// (POST /rooms)
	CreateChatRoom(ctx echo.Context) error
	// Join a chat room
	// (POST /rooms/{id}/join)
	JoinChatRoom(ctx echo.Context, id string) error
	// Leave a chat room
	// (POST /rooms/{id}/leave)
	LeaveChatRoom(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListChatRooms converts echo context to params.
func (w *ServerInterfaceWrapper) ListChatRooms(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListChatRooms(ctx)
	return err
}

// CreateChatRoom converts echo context to params.
func (w *ServerInterfaceWrapper) CreateChatRoom(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateChatRoom(ctx)
	return err
}

// JoinChatRoom converts echo context to params.
func (w *ServerInterfaceWrapper) JoinChatRoom(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.JoinChatRoom(ctx, id)
	return err
}

// LeaveChatRoom converts echo context to params.
func (w *ServerInterfaceWrapper) LeaveChatRoom(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LeaveChatRoom(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/rooms", wrapper.ListChatRooms)
	router.POST(baseURL+"/rooms", wrapper.CreateChatRoom)
	router.POST(baseURL+"/rooms/:id/join", wrapper.JoinChatRoom)
	router.POST(baseURL+"/rooms/:id/leave", wrapper.LeaveChatRoom)

}

type ListChatRoomsRequestObject struct {
}

type ListChatRoomsResponseObject interface {
	VisitListChatRoomsResponse(w http.ResponseWriter) error
}

type ListChatRooms200JSONResponse []ChatRoom

func (response ListChatRooms200JSONResponse) VisitListChatRoomsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateChatRoomRequestObject struct {
	Body *CreateChatRoomJSONRequestBody
}

type CreateChatRoomResponseObject interface {
	VisitCreateChatRoomResponse(w http.ResponseWriter) error
}

type CreateChatRoom200Response struct {
}

func (response CreateChatRoom200Response) VisitCreateChatRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type JoinChatRoomRequestObject struct {
	Id string `json:"id"`
}

type JoinChatRoomResponseObject interface {
	VisitJoinChatRoomResponse(w http.ResponseWriter) error
}

type JoinChatRoom200Response struct {
}

func (response JoinChatRoom200Response) VisitJoinChatRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type LeaveChatRoomRequestObject struct {
	Id string `json:"id"`
}

type LeaveChatRoomResponseObject interface {
	VisitLeaveChatRoomResponse(w http.ResponseWriter) error
}

type LeaveChatRoom200Response struct {
}

func (response LeaveChatRoom200Response) VisitLeaveChatRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List available chat rooms
	// (GET /rooms)
	ListChatRooms(ctx context.Context, request ListChatRoomsRequestObject) (ListChatRoomsResponseObject, error)
	// Create a new chat room
	// (POST /rooms)
	CreateChatRoom(ctx context.Context, request CreateChatRoomRequestObject) (CreateChatRoomResponseObject, error)
	// Join a chat room
	// (POST /rooms/{id}/join)
	JoinChatRoom(ctx context.Context, request JoinChatRoomRequestObject) (JoinChatRoomResponseObject, error)
	// Leave a chat room
	// (POST /rooms/{id}/leave)
	LeaveChatRoom(ctx context.Context, request LeaveChatRoomRequestObject) (LeaveChatRoomResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListChatRooms operation middleware
func (sh *strictHandler) ListChatRooms(ctx echo.Context) error {
	var request ListChatRoomsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListChatRooms(ctx.Request().Context(), request.(ListChatRoomsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChatRooms")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListChatRoomsResponseObject); ok {
		return validResponse.VisitListChatRoomsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateChatRoom operation middleware
func (sh *strictHandler) CreateChatRoom(ctx echo.Context) error {
	var request CreateChatRoomRequestObject

	var body CreateChatRoomJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatRoom(ctx.Request().Context(), request.(CreateChatRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatRoom")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateChatRoomResponseObject); ok {
		return validResponse.VisitCreateChatRoomResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// JoinChatRoom operation middleware
func (sh *strictHandler) JoinChatRoom(ctx echo.Context, id string) error {
	var request JoinChatRoomRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.JoinChatRoom(ctx.Request().Context(), request.(JoinChatRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinChatRoom")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(JoinChatRoomResponseObject); ok {
		return validResponse.VisitJoinChatRoomResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LeaveChatRoom operation middleware
func (sh *strictHandler) LeaveChatRoom(ctx echo.Context, id string) error {
	var request LeaveChatRoomRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveChatRoom(ctx.Request().Context(), request.(LeaveChatRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveChatRoom")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LeaveChatRoomResponseObject); ok {
		return validResponse.VisitLeaveChatRoomResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8STQW/UMBCF/4o1cEybBW65wZ6KFglV3BCHqTPpepV4jD1ZFK3y39HYTbddlrKcekks",
	"e+z3vjf2ASwPgT15SdAcINktDZiH6y3KLfOg4xA5UBRHecW1+pUpEDSQJDp/D3MFHgc6szBXywzf7ciK",
	"li5nryOh0J8KFx+lU853nIud9Lp2S9hffXMDGZUxH7/emCuzKJov3I49QQV7ismxhwbeXa+uV2qLA3kM",
	"Dhr4kKcqCCjb7KiOzEMe3ZPoT+2iOPY3LTSwcUkWiQQVREqBfSo071cr/Vn2Qj5vxhB6Z/P2epfUxBJ9",
	"zleoSL2N1EEDb+pjk+qHDtWP7TmGgjHiVDJpKdnoghRAdWe4M1bzKCBalMZhwDgtBbhH1+NdT8/qKgic",
	"zhCX1j26UOSfIyX5xO30X7SXQD7ck4ymOi5SC43EkebzWT/nXy88xuaDWpNGaymlbuz76SSLomXQePp1",
	"TCIXlUtQH1w71zt2GeR8Op/Z+SfZBIw4kFBM0Hw/gO7MVwuWV6Nv6hStehLS6UP4cQm2mqC2gL8ArGUG",
	"X0DtCff0d9aNLr867IY6+SdqtnrCOs+/AwAA///Z5BbuBQUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
