// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/littlebugger/tinode4chat/internal/service/entity"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockChatRoomRepository is an autogenerated mock type for the ChatRoomRepository type
type MockChatRoomRepository struct {
	mock.Mock
}

type MockChatRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRoomRepository) EXPECT() *MockChatRoomRepository_Expecter {
	return &MockChatRoomRepository_Expecter{mock: &_m.Mock}
}

// AddUserToChatRoom provides a mock function with given fields: ctx, roomID, userID
func (_m *MockChatRoomRepository) AddUserToChatRoom(ctx context.Context, roomID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToChatRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatRoomRepository_AddUserToChatRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToChatRoom'
type MockChatRoomRepository_AddUserToChatRoom_Call struct {
	*mock.Call
}

// AddUserToChatRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockChatRoomRepository_Expecter) AddUserToChatRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockChatRoomRepository_AddUserToChatRoom_Call {
	return &MockChatRoomRepository_AddUserToChatRoom_Call{Call: _e.mock.On("AddUserToChatRoom", ctx, roomID, userID)}
}

func (_c *MockChatRoomRepository_AddUserToChatRoom_Call) Run(run func(ctx context.Context, roomID primitive.ObjectID, userID primitive.ObjectID)) *MockChatRoomRepository_AddUserToChatRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockChatRoomRepository_AddUserToChatRoom_Call) Return(_a0 error) *MockChatRoomRepository_AddUserToChatRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatRoomRepository_AddUserToChatRoom_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, primitive.ObjectID) error) *MockChatRoomRepository_AddUserToChatRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChatRoom provides a mock function with given fields: ctx, room
func (_m *MockChatRoomRepository) CreateChatRoom(ctx context.Context, room entity.ChatRoom) (primitive.ObjectID, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for CreateChatRoom")
	}

	var r0 primitive.ObjectID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ChatRoom) (primitive.ObjectID, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ChatRoom) primitive.ObjectID); ok {
		r0 = rf(ctx, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(primitive.ObjectID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ChatRoom) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatRoomRepository_CreateChatRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChatRoom'
type MockChatRoomRepository_CreateChatRoom_Call struct {
	*mock.Call
}

// CreateChatRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - room entity.ChatRoom
func (_e *MockChatRoomRepository_Expecter) CreateChatRoom(ctx interface{}, room interface{}) *MockChatRoomRepository_CreateChatRoom_Call {
	return &MockChatRoomRepository_CreateChatRoom_Call{Call: _e.mock.On("CreateChatRoom", ctx, room)}
}

func (_c *MockChatRoomRepository_CreateChatRoom_Call) Run(run func(ctx context.Context, room entity.ChatRoom)) *MockChatRoomRepository_CreateChatRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ChatRoom))
	})
	return _c
}

func (_c *MockChatRoomRepository_CreateChatRoom_Call) Return(_a0 primitive.ObjectID, _a1 error) *MockChatRoomRepository_CreateChatRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatRoomRepository_CreateChatRoom_Call) RunAndReturn(run func(context.Context, entity.ChatRoom) (primitive.ObjectID, error)) *MockChatRoomRepository_CreateChatRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatRoomByID provides a mock function with given fields: ctx, id
func (_m *MockChatRoomRepository) GetChatRoomByID(ctx context.Context, id primitive.ObjectID) (*entity.ChatRoom, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatRoomByID")
	}

	var r0 *entity.ChatRoom
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*entity.ChatRoom, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entity.ChatRoom); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ChatRoom)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatRoomRepository_GetChatRoomByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatRoomByID'
type MockChatRoomRepository_GetChatRoomByID_Call struct {
	*mock.Call
}

// GetChatRoomByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockChatRoomRepository_Expecter) GetChatRoomByID(ctx interface{}, id interface{}) *MockChatRoomRepository_GetChatRoomByID_Call {
	return &MockChatRoomRepository_GetChatRoomByID_Call{Call: _e.mock.On("GetChatRoomByID", ctx, id)}
}

func (_c *MockChatRoomRepository_GetChatRoomByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockChatRoomRepository_GetChatRoomByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockChatRoomRepository_GetChatRoomByID_Call) Return(_a0 *entity.ChatRoom, _a1 error) *MockChatRoomRepository_GetChatRoomByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatRoomRepository_GetChatRoomByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*entity.ChatRoom, error)) *MockChatRoomRepository_GetChatRoomByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromChatRoom provides a mock function with given fields: ctx, roomID, userID
func (_m *MockChatRoomRepository) RemoveUserFromChatRoom(ctx context.Context, roomID primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromChatRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatRoomRepository_RemoveUserFromChatRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromChatRoom'
type MockChatRoomRepository_RemoveUserFromChatRoom_Call struct {
	*mock.Call
}

// RemoveUserFromChatRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID primitive.ObjectID
//   - userID primitive.ObjectID
func (_e *MockChatRoomRepository_Expecter) RemoveUserFromChatRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockChatRoomRepository_RemoveUserFromChatRoom_Call {
	return &MockChatRoomRepository_RemoveUserFromChatRoom_Call{Call: _e.mock.On("RemoveUserFromChatRoom", ctx, roomID, userID)}
}

func (_c *MockChatRoomRepository_RemoveUserFromChatRoom_Call) Run(run func(ctx context.Context, roomID primitive.ObjectID, userID primitive.ObjectID)) *MockChatRoomRepository_RemoveUserFromChatRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockChatRoomRepository_RemoveUserFromChatRoom_Call) Return(_a0 error) *MockChatRoomRepository_RemoveUserFromChatRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatRoomRepository_RemoveUserFromChatRoom_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, primitive.ObjectID) error) *MockChatRoomRepository_RemoveUserFromChatRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatRoomRepository creates a new instance of MockChatRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRoomRepository {
	mock := &MockChatRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
